version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Cleaning project..."
      - mvn clean

  build:
    commands:
      - echo "Packaging project..."
      - mvn package -DskipTests
      - mkdir -p build
      - cp target/*.jar build/

  post_build:
    commands:
      - echo "Zipping JAR for Elastic Beanstalk..."
      - cd build
      - zip ../app.zip *.jar
      - cd ..
      - echo "Build completed."

artifacts:
  files:
    - app.zip
