version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package -DskipTests
      - cp target/devopsapp-1.0.0.jar app.jar
      - zip springboot-app.zip app.jar

artifacts:
  files:
    - springboot-app.zip
