version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  pre_build:
    commands:
      - echo "Cleaning previous builds"
      - mvn clean

  build:
    commands:
      - echo "Building the application"
      - mvn package -DskipTests
      - echo "Copying JAR to output directory"
      - mkdir -p build
      - cp target/*.jar build/

  post_build:
    commands:
      - echo "Zipping the JAR for Elastic Beanstalk"
      - cd build
      - zip ../app.zip *.jar
      - cd ..
      - echo "Build completed on `date`"

artifacts:
  files:
    - app.zip
