version: '3.8'

services:
  devops-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-app:latest
    container_name: devops-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo
      - rabbitmq
      - memcached

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11212:11211"

volumes:
  mongo-data:
